name: Vehicles
author: JaxkDev
version: 0.0.3
api: [4.0.0]
mcpe-protocol: [361]
main: JaxkDev\Vehicles\Main
website: "https://github.com/JaxkDev/Vehicles"
description: "[W.I.P] PocketMine-MP plugin that brings vehicles to your server !"

commands:
  vehicles:
    description: "Vehicles general command"
    permission: vehicles.command.use
    usage: /vehicles help
    permission-message: "[Vehicles] > You do not have permission to use vehicle commands."

permissions:
  vehicles:
    default: false
    description: "Toggles all vehicles plugin perms."
    children:

      vehicles.command:
        description: "Toggles all vehicle commands."
        default: false
        children:

          vehicles.command.use:
            description: "Allows user to use commands."
            default: true
          vehicles.command.spawn:
            description: "Allows user to spawn a vehicle."
            default: op
          vehicles.command.remove:
            description: "Allows user to remove a vehicle."
            default: op
          vehicles.command.lock:
            description: "Allows user to lock their vehicles."
            default: true
          vehicles.command.unlock:
            description: "Allows user to unlock their vehicles."
            default: true
          vehicles.command.giveaway:
            description: "Allows user to giveaway their vehicles (lose ownership)."
            default: true

      vehicles.drive:
        description: "Allows user to drive their vehicle or a unlocked one."
        default: true
      vehicles.passenger:
        description: "Allows user to be a passenger in any vehicle unlocked."
        default: true